### ISSUE TITLE
[Enhancement] Announcement in chat when player lists an item

### ISSUE THREAD

**Issue by Shybella** [xKaYoz/AkarianAuctionHouse#1]
Announcement in chat that x player has listed y item for z price. 

Example
" Swaggy has added Diamond for $100" and this gets announced in chat.

**Comment by xKaYoz** [comment]
Hey, Thank you for the suggestion! I plan to implement this in a future update with the option for players to disable the notification! I'll let you know when I have it added!

**Comment by xKaYoz** [comment]
Hey @Shybella, I have posted the update that includes your suggestion. Thanks again!
