### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid UUID string: 000000000000000000390218df83jm

### ISSUE THREAD

**Issue by AGuyNamedJens** [xKaYoz/AkarianAuctionHouse#10]
Randomly since bedrock players using GeyserMC the plugin no longer shows the auction list, throws this error. Other plugins work fine by disabling the UUID validator such as LuckPerms using a special config option for it. Should probably fix it?

**Comment by AGuyNamedJens** [comment]
at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at net.akarian.auctionhouse.utils.NameManager.getName(NameManager.java:82) ~[AuctionHouse (1).jar:?]
        at net.akarian.auctionhouse.utils.NameManager.getName(NameManager.java:34) ~[AuctionHouse (1).jar:?]
        at net.akarian.auctionhouse.listings.Listing.createActiveListing(Listing.java:303) ~[AuctionHouse (1).jar:?]
        at net.akarian.auctionhouse.guis.AuctionHouseGUI.updateInventory(AuctionHouseGUI.java:410) ~[AuctionHouse (1).jar:?]
        at net.akarian.auctionhouse.guis.AuctionHouseGUI.getInventory(AuctionHouseGUI.java:213) ~[AuctionHouse (1).jar:?]
        at net.akarian.auctionhouse.commands.main.AuctionHouseCommand.onCommand(AuctionHouseCommand.java:36) ~[AuctionHouse (1).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by AGuyNamedJens** [comment]
Looks like it happends on the list feature, when the author is a bedrock user who has no microsoft account (which means, they don't have a java account). I've found 3 listings from a bedrock user, they have the 0000000 UUID, which seems to break the whole plugin.. and now the auction house is unusable

**Comment by AGuyNamedJens** [comment]
https://github.com/xKaYoz/AkarianAuctionHouse/blob/9a3a1a9869977b0b9057a6b54004d7bddbf7020f/src/main/java/net/akarian/auctionhouse/utils/NameManager.java#L59 This whole method seems to never check the UUIDs of Bedrock players since you're checking against active java accounts, while GeyserMC doesn't require all accounts to be java specific when using floodgate, you should check against GeyserMC's FUUID's for naming bedrock players @xKaYoz ?

**Comment by xKaYoz** [comment]
Hey there @AGuyNamedJens!

I am only vaguely familiar with geyser and all of its workings and how people implement it. I was reading up and am thinking of adding an option to use the Floodgate API. I am unsure how widely used it is, do you run the Floodgate plugin on your server?

Thanks!

**Comment by AGuyNamedJens** [comment]
> Hey there @AGuyNamedJens!
> 
> I am only vaguely familiar with geyser and all of its workings and how people implement it. I was reading up and am thinking of adding an option to use the Floodgate API. I am unsure how widely used it is, do you run the Floodgate plugin on your server?
> 
> Thanks!

Yes, Without the Floodgate plugin players are forced to use their Xbox("Java") account. I allow mobile and console players in my server, this is the first time i noticed the bug. Players can't open the GUI at all anymore.

You should research into the "fuuid" logic geyser/floodgate have, it should be as simple as a check for bukkit user UUIDs.

EssentialsX and LuckPerms do not have any issues with bedrock players, maybe look into those?

**Comment by xKaYoz** [comment]
Hey there @AGuyNamedJens!

Are you perhaps referring to the XUID? I haven't seen any mention yet of a FUUID but rather XUIDs.

Thanks!

**Comment by AGuyNamedJens** [comment]
No idea, I'm not known with java yet haha, I meant the uuids created by geyser/floodgate, so i assume yes.

**Comment by xKaYoz** [comment]
Hey there @AGuyNamedJens!

I was finally able to get my geyser setup working so I was able to test and find out a few things. I was able to find out that all bedrock players get generated the long 0 UUID. I also found out that the server is able to recognize those player's to their associated UUID's with no issue. The only thing that I found was when one of the bedrock players were offline, that it would send the error in console because it did not keep them saved.

What I am planning on doing to circumvent this is adding an area in the user database to store their username with the UUID since they keep the same UUID upon rejoining. Upon my initial testing it is seeming to work without issue.

**Since I am not testing with bedrock accounts with no java accounts, would you be able to verify that they also keep the same UUIDs each login?**

Thanks!

**Comment by AGuyNamedJens** [comment]
> Hey there @AGuyNamedJens!
> 
> I was finally able to get my geyser setup working so I was able to test and find out a few things. I was able to find out that all bedrock players get generated the long 0 UUID. I also found out that the server is able to recognize those player's to their associated UUID's with no issue. The only thing that I found was when one of the bedrock players were offline, that it would send the error in console because it did not keep them saved.
> 
> What I am planning on doing to circumvent this is adding an area in the user database to store their username with the UUID since they keep the same UUID upon rejoining. Upon my initial testing it is seeming to work without issue.
> 
> **Since I am not testing with bedrock accounts with no java accounts, would you be able to verify that they also keep the same UUIDs each login?**
> 
> Thanks!

As far as i'm aware, UUIDs never change, usernames do. Also the UUIDs only change when they link their account to their java account, but i assume no one would be so stupid to play before verifying if they own an account. You should maybe check for any username changes, idk tbh. Adding the username to the database definitely sounds like a good idea.

Also, Yeah, sometimes the bedrock players are known, but on server restarts they're not recognized by this plugin (they are on EssentialsX, Luckperms etc...

**Comment by AGuyNamedJens** [comment]
Any updates on this? Players now officially left the server due to Auction House being offline for 5 days now..

**Comment by AGuyNamedJens** [comment]
@xKaYoz

**Comment by xKaYoz** [comment]
Hey there @AGuyNamedJens.

Sorry about the delayed time with responses, I've had some work come up and school to catch up on. I will post this as soon as I can. I just have to get some finishing touches and bug tests.

Thanks!

**Comment by AGuyNamedJens** [comment]
> Hey there @AGuyNamedJens.
> 
> Sorry about the delayed time with responses, I've had some work come up and school to catch up on. I will post this as soon as I can. I just have to get some finishing touches and bug tests.
> 
> Thanks!

That's understandable, though it's been a critical bug that completely disabled the use of the auction house for more than a week now.
