### ISSUE TITLE
IT HAS DUPE + Can't change main title

### ISSUE THREAD

**Issue by Evalutik** [xKaYoz/AkarianAuctionHouse#11]
If we put things up for auction, then change the quantity that is sold to smaller amount and then restart the server, we will see that the things that were given to us remained in the inventory, but the number of things did not change at the auction! Therefore, now we can take what is on the auction and get additional things!

+ There is no way to change the inscription "AuctionHouse" in the main menu at the top, and title of the Confirm Gui

**Comment by xKaYoz** [comment]
Hey there @Evalutik.

Thanks for bringing this to my attention. Sorry for the delay in getting this addressed, but I have fixed this and it will be posted as soon as I can.

Thanks again!
