### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by Antonekkk** [xKaYoz/AkarianAuctionHouse#14]
Hello,
the plugin doesn't work and says it didn't find any Economy plugin, while I'm using CMI and Vault.

[INFO] [AuctionHouse] Enabling AuctionHouse v1.2.1
20:02:38[INFO] [AuctionHouse] ========== Akarian Auction House ==========
20:02:38[INFO] [AuctionHouse]
20:02:38[INFO] [AuctionHouse] Loading Akarian Auction House v1.2.1...
20:02:39[INFO] [AuctionHouse] Setting up Economy...
20:02:39[INFO] AuctionHouse » AuctionHouse has failed to detect an economy. The plugin is now disabling
20:02:39[INFO] [AuctionHouse] Zipped log 2023-03-13-001.
20:02:39[INFO] [AuctionHouse] =================================================

**Comment by xKaYoz** [comment]
Hello there.

Sorry for the late reply. After doing my own research it seems like there is a setting in the CMI plugin to enable vault compatibility. Have you ensured that you have enabled this option?

Thanks!
