### ISSUE TITLE
[BUG] Listing Time is not configurable

### ISSUE THREAD

**Issue by compuvin** [xKaYoz/AkarianAuctionHouse#16]
**Describe the bug**
The default listing time is 24 hours or 86400 seconds. Changing the value of the listing time in the config.yml seems to be reverted when the plugin is reloaded. Thus 24 hours is the only available option for how long an item will be listed.

**To Reproduce**
Edit the listing time value in the config.yml file to a value other than 86400 and reload the plugin. 

**Expected behavior**
I would expect if I double the default value I would be able to list an item for 2 days.

**Server Type and Version:**
Spigot 1.19.4-R0.1

**Additional context**
Let me know if you need any additional information or help testing.

**Comment by xKaYoz** [comment]
Hey there!

When reloading the plugin, are you using /reload or are you using /ah reload or are you restarting the server?

Thanks!

**Comment by xKaYoz** [comment]
You can also change the time ingame in the “/aha settings” menu

**Comment by compuvin** [comment]
I was restarting the server. I used the /aha reload command and it worked!
The /aha settings menu does not work however. I get an "internal error message has occurred" error message.

**Comment by xKaYoz** [comment]
Hey there!

Would you mind to send me the entire error message that was shown?

Thanks!

**Comment by xKaYoz** [comment]
Closing issue due to no reply. Changed the way the config saves to fix this issue.
