### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Antonekkk** [xKaYoz/AkarianAuctionHouse#17]
Hi, your plugin is quite choppy on the server and requires a load on the server.

https://ctrlv.cz/GC6w

**Comment by xKaYoz** [comment]
Hey there!

I greatly appreciate the feedback as I am working on making optimizations to make it a nicer experience. If you don't mind to keep me updated on how it is running I would appreciate it.

Thank you!

**Comment by xKaYoz** [comment]
Closing issue due to no reply. Optimization changes have been implemented in newest versions.
