### ISSUE TITLE
[Suggestion] Item Blacklist

### ISSUE THREAD

**Issue by FireML** [xKaYoz/AkarianAuctionHouse#18]
**Describe the solution you'd like**
Ability to blacklist certain items from the Auction House based on Material, Lore, or Display Name.

Adding this will be helpful for servers that do not want specific items to be sold. The Lore and Display Name would allow you to blacklist Custom Items.

**Comment by xKaYoz** [comment]
Thanks for the suggestion! This feature has been added to the next update and will be available with the next release.

Thanks!
