### ISSUE TITLE
No balance/money command

### ISSUE THREAD

**Issue by madskii** [xKaYoz/AkarianAuctionHouse#19]
Hi, I love the plugin but my players on my server cannot do a command such as /balance or /money to check their balances, i have Vault, Essentials X, LuckPerms and this plugin, and was wondering if there was a permission to allow for them to be able to do that command.

**Comment by xKaYoz** [comment]
Hey there!

This plugin does not edit the commands for /balance or /money. We’re the commands working before the plugin was installed?

Thanks!
