### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Xteri08** [xKaYoz/AkarianAuctionHouse#22]
**Describe**
So basically when you or a player has inventory full and buys a item it doesnt drop at his feet neither it comes to the chest but your balance is gone along with the stuff you just buyed.

**To Reproduce**
1.List something on auction.
2.Fill your inventory on another account.
3.Buy the thing

**Expected behavior**
It shall be either dropping the item or shall be saying to the player that your inventory us full and making the trade discarded

**Screenshots**
Well i cant add screenshot as its not possible.

**Server Type and Version:**
purpur-1.19.3
type-SMP

**Additional context**
May be you can add a confirmation before buying iteam and drop it on the players feet

**Comment by xKaYoz** [comment]
Hey there!

thank you for the bug report, I greatly appreciate it. This bug has been reported in the discord and I have made a fix to it where it will be found in the reclaim GUI. I will let you know when I push the fix out to the public. 

Thank you again!

**Comment by Xteri08** [comment]
thanks sir
