### ISSUE TITLE
[BUG] There is no way to limit auctions

### ISSUE THREAD

**Issue by kalleswe** [xKaYoz/AkarianAuctionHouse#27]
There is no way of limiting auctions for individual users and/or groups.
You need to set a permission like auctionhouse.limit.<num>
Where <num> is the max number of active auctions a user may have at the same time.
Otherwise this plugin will break server economy quite quickly.

Also, you need to add a block list for certain items (which should be able to match on item name/lore etc)

**Comment by xKaYoz** [comment]
Both of these features are already developed. The max listings exist in the form of a permission “auctionhouse.listings.#” and the black listing will be available in the next release.
