### ISSUE TITLE
[BUG] Bought items lost on inventory full

### ISSUE THREAD

**Issue by kalleswe** [xKaYoz/AkarianAuctionHouse#28]
When the inventory of a player is full and he buys somthing from AH, the auction goes through and the item disappears and he never gets it. AH should say that his inventory is full and he can't buy then.

**Comment by xKaYoz** [comment]
Hey there!

What version of the plugin are you running? The latest version will allow the player to purchase the auction house but the listing gets placed into their unclaimed listings, the same area the expired listings go.

**Comment by vertanzil** [comment]
Hey @xKaYoz 

I am the head of development for isoVerse and we have a similar problem, see ticket below 
![image](https://github.com/xKaYoz/AkarianAuctionHouse/assets/73062855/3666e5a8-b0d6-4ef9-ab62-6611dfa03a34)


Do you have any time line of when this will be fixed?

Regards
Vert

**Comment by xKaYoz** [comment]
Hey @vertanzil

I believe this same bug has been reported on the discord and i have made a fix for that for the next update. I am finishing some admin GUI things before I post the update. I can send you a build of it to test and try and recreate this issue to see if it is solved. 

Thanks!

**Comment by vertanzil** [comment]
> Hey @vertanzil
> 
> I believe this same bug has been reported on the discord and i have made a fix for that for the next update. I am finishing some admin GUI things before I post the update. I can send you a build of it to test and try and recreate this issue to see if it is solved. 
> 
> Thanks!

Hi @xKaYoz 

That sounds good do you want to send me that over discord? or is there somewhere i can go to download it and er can test it out?

Let me know and I can sort that out.

Thanks
Vertanzil

**Comment by xKaYoz** [comment]
> > Hey @vertanzil
> > I believe this same bug has been reported on the discord and i have made a fix for that for the next update. I am finishing some admin GUI things before I post the update. I can send you a build of it to test and try and recreate this issue to see if it is solved.
> > Thanks!
> 
> Hi @xKaYoz
> 
> That sounds good do you want to send me that over discord? or is there somewhere i can go to download it and er can test it out?
> 
> Let me know and I can sort that out.
> 
> Thanks Vertanzil

If you wouldn’t mind to message me on discord or join the server I can send it via pm!

Thanks!
