### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zapry** [xKaYoz/AkarianAuctionHouse#31]
**Describe the bug**
Plugin is literally broken

**To Reproduce**
Just restarting server

**Expected behavior**
Start properly

**Screenshots**
(https://bin.bloom.host/bemasofate.properties) this is the log

**Server Type and Version:**
Pufferfish version git-Pufferfish-22 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

**Additional context**

**Comment by xKaYoz** [comment]
You are not using the latest version
