### ISSUE TITLE
[BUG] Lore in 1.3.1-b4

### ISSUE THREAD

**Issue by makegodhere** [xKaYoz/AkarianAuctionHouse#32]
**Describe the bug**
Broken lore on listing item

**To Reproduce**
Just list item

**Expected behavior**
List item

**Screenshots**
![image](https://github.com/xKaYoz/AkarianAuctionHouse/assets/28805838/b87850a3-fd5d-4867-8bc6-c1b2954d765c)
![image](https://github.com/xKaYoz/AkarianAuctionHouse/assets/28805838/3132326c-f446-4fc0-9504-3a38c6e2635a)

**Server Type and Version:**
1.20.2
1.3.1-b4

**Additional context**
No else

**Comment by Xteri08** [comment]
ya its happening with my server too

**Comment by xKaYoz** [comment]
I greatly apologize about this issue and any issues that were caused by it. I have released the next build that patches this issue.

https://github.com/xKaYoz/AkarianAuctionHouse/releases/tag/1.3.1-b5

Thank you!

**Comment by makegodhere** [comment]
> I greatly apologize about this issue and any issues that were caused by it. I have released the next build that patches this issue.
> 
> https://github.com/xKaYoz/AkarianAuctionHouse/releases/tag/1.3.1-b5
> 
> Thank you!

Amazing plugin! Do not stop  ♥
