### ISSUE TITLE
Communications exception MySQL

### ISSUE THREAD

**Issue by AGuyNamedJens** [xKaYoz/AkarianAuctionHouse#9]
[21:49:47] [Craft Scheduler Thread - 897 - AuctionHouse/WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 43,212,895 milliseconds ago. The last packet sent successfully to the server was 43,212,895 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

Either you forgot to disconnect/reconnect on need, or something's wrong

**Comment by xKaYoz** [comment]
Hey @AGuyNamedJens!

Thanks for bringing this to my attention! I have adjusted my connection checker to ensure a continuous active connection. I will have it posted in the next update.

Thanks again!

**Comment by AGuyNamedJens** [comment]
Thank you :) btw about that update request to allow ranks getting discounts using permissions. Please make that it can be any amount 00.00% like essentials's Sethome ranks and probably round it as well

**Comment by AGuyNamedJens** [comment]
Ontop of that for some reason i fixed that connection issue by adding the autoReconnect after the table name in the configuration file, shouldn't you check such extra variables to prevent possible malicious injections either?

**Comment by xKaYoz** [comment]
Hey there @AGuyNamedJens!

I do see where you are coming from with that. I assumed that since only the administrators, or who you deem to be trustworthy to have access to either the admin commands ingame or FTP, that an issue would not arise but I will be sure to look it over some more.

Thanks!

**Comment by AGuyNamedJens** [comment]
> Hey there @AGuyNamedJens!
> 
> I do see where you are coming from with that. I assumed that since only the administrators, or who you deem to be trustworthy to have access to either the admin commands ingame or FTP, that an issue would not arise but I will be sure to look it over some more.
> 
> Thanks!

It's just common programming security tbh, I atleast assume other plugins prevent such things at a low level as well, there's always people that are stupid enough to mess up their access.
Atleast, it's known to be a must to protect on anything that communicates with public instances
